name: Get pods
on: [push]
env:
    AWS_REGION: us-east-1
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    - name: Configure kubectl
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.DEMO_KUBECONFIG }}
      with:
        args: get pods